# Setup
title:               //starol.is/
tagline:             'The idea spring'
description:         'A place for ideas to express themself'
url:                 http://starolis.github.io/lanyon
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Matt Starolis
  url:               https://twitter.com/mattstarolis
  email:             matt@starol.is

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
